#define ASPECT_WEIGHT_MEDIEVAL 100
#define ASPECT_WEIGHT_BLUESPACE 70
#define ASPECT_WEIGHT_TRAPS 60
#define ASPECT_WEIGHT_DEPRESSION 50
#define ASPECT_WEIGHT_GOLODOMOR 40
#define ASPECT_WEIGHT_NORMAL 0
#define ASPECT_WEIGHT_MINIMAL -100
